export const gameplayConfig = {
    POWERUP_TYPE_MAGNET: 'magnet',
    POWERUP_DURATION: 10,
    POWERUP_TYPE_DOUBLER: 'doubler',
    // Magnet visual effect
    MAGNET_EFFECT_COLOR: 0xff0000,
    MAGNET_EFFECT_EMISSIVE: 0x330000,
    MAGNET_EFFECT_METALNESS: 0.9,
    MAGNET_EFFECT_ROUGHNESS: 0.1,
    // Doubler visual effect
    DOUBLER_EFFECT_COLOR: 0x0088FF,
    DOUBLER_EFFECT_EMISSIVE: 0x002244,
    DOUBLER_EFFECT_METALNESS: 0.7,
    DOUBLER_EFFECT_ROUGHNESS: 0.2,

    DEFAULT_COIN_SCORE: 10,
    MAGNET_POWERUP_RADIUS: 80,
    MAGNET_POWERUP_FORCE: 150,
    COIN_COLLECTION_RADIUS_FACTOR: 1.5,
    PLAYER_SAFE_DISTANCE_FACTOR: 0.2,
    TREE_COLLISION_BUFFER: 0.2,
    DOUBLER_MULTIPLIER: 2,
    DOUBLER_COLLISION_RADIUS: 1.0,
};
